/**
 * Guides added in update-134 (search and AI engines). Same rules as the rest:
 * every claim must be true on sasa today.
 */
import type { Article } from "./articles";

export const NEW_ARTICLES: Article[] = [
  {
    slug: "how-to-launch-a-meme-coin-on-base",
    title: "How to launch a meme coin on Base: a step-by-step guide",
    description:
      "Everything you need to launch a meme coin on Base: what it costs, the steps, how a bonding curve launch works and how to give your coin a fair start.",
    date: "2026-10-06",
    updated: "2026-10-06",
    readMin: 7,
    summary: "From idea to a live coin on Base in a few minutes, with no code and no upfront liquidity.",
    tags: ["launch", "base", "beginner"],
    takeaways: [
      "You can launch a meme coin on Base without code: a name, a ticker and a picture are enough.",
      "On sasa the launch itself is free and everything is priced in USDC.",
      "A new coin starts on a [bonding curve](/learn/what-is-a-bonding-curve/), so you don't need to put up liquidity.",
      "You can launch on Base and Robinhood Chain at the same time with one form.",
    ],
    body: [
      { p: "Base is an Ethereum layer 2 network run by Coinbase. Fees are low, wallets support it out of the box and a large share of on-chain meme coin trading happens there. That makes it one of the easiest places to launch a meme coin. This guide covers the whole process, start to finish." },
      { h2: "What you need" },
      { ul: [
        "An idea people can get in one sentence. The best meme coins are easy to explain and easy to share.",
        "A name, a short ticker (3 to 6 letters works best) and a square picture.",
        "An account on a launchpad. On sasa an email address is enough: a wallet is created for you and network fees are covered.",
        "Optional: a little USDC if you want to buy some of your own coin at launch.",
      ] },
      { h2: "Step by step" },
      { ol: [
        "Open [Create](/create/) and choose Base. You can also keep Robinhood Chain selected to launch on both at once.",
        "Enter the name, ticker, picture and a short description. If you only have an idea, the AI option turns one sentence into a name, ticker, story and logo.",
        "Pick your options: whether to lock your own coins for a while, where your share of trading fees goes, and whether to make a first buy.",
        "Confirm. The coin goes live on its bonding curve in seconds and gets its own page, chart and holder map.",
        "Share the link. The coin page shows the price, the chart, the [first buyers](/learn/meme-coin-first-buyers/) and how close it is to graduation.",
      ] },
      { tip: "Buying a small amount of your own coin at launch is normal. Buying a large share and selling it later is what people look for when they check a new coin, so keep it modest or lock it." },
      { h2: "What it costs" },
      { p: "Launching on sasa is free. Each trade on the curve has a small fee, part of which goes to the coin's creator; the details are on the [Help](/help/) page. With an email account you never need ETH for network fees." },
      { h2: "What happens after launch" },
      { p: "Every buy raises the price along the curve and moves the coin toward its graduation target. When the target is reached, the money and a matching amount of coins become a Uniswap pool whose liquidity is locked forever. [Graduation explained](/learn/meme-coin-graduation-explained/) covers it in detail." },
      { h2: "How to give your coin a fair start" },
      { ul: [
        "Keep your own buy small, or use the creator lock so buyers can see you can't sell right away.",
        "Don't split your coins across several wallets. Linked wallets show up on the coin page and put buyers off; see [bundled launches](/learn/bundled-meme-coin-launches/).",
        "Post the coin page link, not just the contract address, so people can check the chart and holders before they buy.",
      ] },
    ],
    faq: [
      { q: "How much does it cost to launch a meme coin on Base?", a: "On sasa the launch is free. You only pay if you choose to buy some of your own coin." },
      { q: "Do I need ETH on Base?", a: "Not with an email account on sasa: network fees are covered and everything is in USDC. With your own wallet you need a little ETH on Base." },
      { q: "Can I launch on Base and Robinhood Chain at the same time?", a: "Yes. Keep both chains selected on Create and the coin goes live on both at once, with one shared graduation target." },
      { q: "Do I need to add liquidity?", a: "No. The bonding curve sells the coin directly until graduation, when liquidity is created and locked automatically." },
    ],
  },
  {
    slug: "meme-coin-first-buyers",
    title: "What a meme coin's first buyers tell you (and how to read them)",
    description:
      "How to read a meme coin's first buyers: who got in early, how much they paid, whether they still hold, and the patterns that signal a fair or a rigged launch.",
    date: "2026-10-06",
    updated: "2026-10-06",
    readMin: 6,
    summary: "The first 30 wallets into a coin say more about it than any chart.",
    tags: ["safety", "holders", "research"],
    takeaways: [
      "A coin's first buyers show whether the launch was fair or set up for a few wallets.",
      "Check three things: how much they bought, whether they still hold, and whether they are linked to each other.",
      "Many early buyers still holding is a good sign; most early buyers already gone is a warning.",
      "On sasa every coin page has a Who bought table with exactly these facts.",
    ],
    body: [
      { p: "The first minutes of a meme coin decide a lot. Whoever buys first buys cheapest, and if a handful of wallets take most of the early supply, everyone who comes later is buying from them. Looking at the first buyers takes less than a minute and tells you who you would be trading with." },
      { h2: "Where to find them" },
      { p: "On sasa, open any coin and scroll to Who bought. It lists the first 30 wallets that bought, in order, with what each one spent and the share of the supply it still holds. Wallets are tagged Creator, You or Linked where that applies." },
      { h2: "What to look at" },
      { ol: [
        "Size: were the first buys small and varied, or a few large buys within seconds?",
        "Still holding: how much of the supply do the first buyers still hold, and how many sold everything?",
        "Links: are some first buyers tagged Linked, meaning they sent the coin to each other?",
        "The creator: did the creator buy a big share early? Is it locked?",
      ] },
      { h2: "Good signs" },
      { ul: [
        "Many different wallets with small to medium buys.",
        "A healthy part of the early buyers still holding after the first hours.",
        "No linked wallets, or only a couple with small amounts.",
        "A creator with a modest stake, ideally locked.",
      ] },
      { h2: "Warning signs" },
      { ul: [
        "A few wallets bought most of the early supply within the first blocks.",
        "Several first buyers are linked: often one person spreading a bag across wallets.",
        "Most first buyers already sold everything while new buyers keep arriving.",
        "The creator holds a large unlocked share.",
      ] },
      { tip: "One warning sign isn't proof of anything. Two or three together usually mean the early buyers are waiting for you to buy so they can sell." },
      { h2: "Combine it with the holder map" },
      { p: "Who bought tells you about the start; the holder map shows the coin today. Big bubbles joined by dashed lines are linked wallets holding a lot together. Read both, then the chart. [How to spot a rug pull](/learn/how-to-spot-a-meme-coin-rug-pull/) has the full checklist." },
    ],
    faq: [
      { q: "What does Linked mean on sasa?", a: "The wallet sent this coin to, or received it from, another wallet in the list. It often means one person controls several wallets." },
      { q: "Is it bad if the creator bought first?", a: "Not by itself: creators often buy a little at launch. It matters how much, and whether the coins are locked." },
      { q: "Why do first buyers matter after the launch?", a: "They hold the cheapest coins. If they own a big share, their selling can move the price a lot." },
    ],
  },
  {
    slug: "bundled-meme-coin-launches",
    title: "Bundled meme coin launches: how to spot linked wallets before you buy",
    description:
      "What a bundled launch is, why creators split supply across wallets, and the simple checks that reveal linked wallets on any meme coin.",
    date: "2026-10-06",
    updated: "2026-10-06",
    readMin: 6,
    summary: "One person, many wallets: how bundles hide a big holder and how to see through them.",
    tags: ["safety", "holders", "bundles"],
    takeaways: [
      "A bundled launch is when one person buys a big share of a new coin through many wallets, so no single wallet looks large.",
      "Bundles make a coin look more widely held than it is, and they can all sell at once.",
      "Wallets that send the coin to each other are the clearest clue; sasa marks them as Linked.",
      "Check the Linked share on the holder map and the Linked tags in Who bought before buying.",
    ],
    body: [
      { p: "Most people check the top holders before buying a meme coin. If no wallet holds more than a few percent, the coin looks safe. Bundles exist to beat exactly that check: the same person buys through ten or twenty wallets at launch, so each one looks small." },
      { h2: "Why bundles are a problem" },
      { ul: [
        "The real concentration is hidden: twenty wallets with 2% each can be one holder with 40%.",
        "They can sell at the same moment, which drops the price far more than any single wallet could.",
        "They make a launch look busier than it is, which pulls in real buyers.",
      ] },
      { h2: "How to spot them" },
      { ol: [
        "Linked wallets: on sasa, wallets that sent the coin to each other are joined by dashed lines on the holder map and tagged Linked in Who bought.",
        "The Linked share: the holder map shows how much of the supply linked wallets hold together. Over about 10% deserves a closer look.",
        "Timing: many buys of similar size in the first seconds of a launch.",
        "Same funding: wallets funded from the same source just before the launch. A block explorer shows where each wallet's money came from.",
      ] },
      { tip: "Linked isn't always bad: people move coins between their own wallets. It is the size that matters. A few linked wallets with tiny amounts is noise; a linked group with a third of the supply is a bundle." },
      { h2: "What to do if you find one" },
      { ul: [
        "Assume the group can sell at any time and size your buy for that.",
        "Set a stop loss so a sudden dump doesn't take you all the way down. See [take profit and stop loss](/learn/take-profit-stop-loss-meme-coins/).",
        "Prefer coins where the creator's coins are locked and no group dominates the early supply.",
      ] },
    ],
    faq: [
      { q: "What is a bundled launch?", a: "One person buying a large share of a new coin through many wallets at launch, so the holdings look spread out." },
      { q: "How does sasa find linked wallets?", a: "From the coin's transfers on chain: wallets that sent the coin to each other are linked." },
      { q: "Can a bundle be hidden completely?", a: "Not always caught by transfers alone. That's why timing and funding are worth checking too." },
    ],
  },
  {
    slug: "how-to-read-a-meme-coin-chart",
    title: "How to read a meme coin chart: candles, volume and market cap",
    description:
      "A plain guide to meme coin charts: what candles and volume bars mean, why the chart shows market cap, which time frame to use and the patterns worth knowing.",
    date: "2026-10-06",
    updated: "2026-10-06",
    readMin: 7,
    summary: "Candles, volume and time frames in plain words, for coins that move fast.",
    tags: ["trading", "charts", "beginner"],
    takeaways: [
      "Each candle shows where the price opened, closed, and how high and low it went in that time frame.",
      "Volume bars show how much was traded; moves on high volume mean more than moves on low volume.",
      "Meme coin charts often show market cap instead of a tiny price, which makes them easier to read.",
      "Use 1 or 5 minute candles for a new coin and 1 hour or 1 day for an older one.",
    ],
    body: [
      { p: "A meme coin can move 50% in a few minutes, so its chart is worth reading carefully. The good news: you only need a handful of ideas to read it well." },
      { h2: "Candles" },
      { p: "Each candle covers one time frame, say 5 minutes. The body runs from the opening price to the closing price: green if it closed higher, red if lower. The thin lines above and below, the wicks, show the highest and lowest price reached in that time." },
      { ul: [
        "Long green bodies: buyers in control.",
        "Long upper wicks: the price went up but got sold back down.",
        "Long lower wicks: the price dropped but buyers stepped in.",
      ] },
      { h2: "Volume" },
      { p: "The bars at the bottom show how much was traded in each candle. A price move on big volume has many people behind it; the same move on tiny volume can reverse just as fast. On new coins, a few large trades can make the chart look dramatic, so check volume before reading too much into a candle." },
      { h2: "Why the chart shows market cap" },
      { p: "Meme coins often cost a fraction of a cent, with many zeros. sasa's chart shows market value instead: the price times the supply. It moves exactly like the price but reads like $45K or $1.2M. [Market cap vs FDV vs liquidity](/learn/meme-coin-market-cap-vs-fdv-vs-liquidity/) explains the numbers." },
      { h2: "Which time frame to use" },
      { ul: [
        "First hour of a coin: 1 minute or 5 minute candles.",
        "First day: 15 minutes to 1 hour.",
        "Older coins: 4 hours or 1 day to see the trend.",
      ] },
      { h2: "Patterns worth knowing" },
      { ul: [
        "A steady climb with rising volume: real demand building.",
        "One huge green candle, then a slow bleed: an early buyer or a bundle selling into new buyers.",
        "Higher lows after a drop: buyers defending a level.",
        "Flat chart, no volume: no attention. A coin needs buyers to move.",
      ] },
      { tip: "On sasa you can set price alerts and take profit or stop loss right from the coin page, so you don't have to watch the chart all day." },
    ],
    faq: [
      { q: "What do green and red candles mean?", a: "Green: the price closed higher than it opened in that time frame. Red: it closed lower." },
      { q: "Why does sasa show market cap on the chart?", a: "Because meme coin prices have many zeros. Market cap moves the same way and is easier to read." },
      { q: "What time frame is best for new meme coins?", a: "1 or 5 minute candles in the first hour, then longer frames as the coin gets older." },
    ],
  },
  {
    slug: "meme-coin-glossary",
    title: "Meme coin glossary: the terms every trader should know",
    description:
      "Plain definitions of the words meme coin traders use: bonding curve, graduation, CA, market cap, FDV, liquidity, bundle, sniper, rug pull, dev lock and more.",
    date: "2026-10-06",
    updated: "2026-10-06",
    readMin: 9,
    summary: "From ape to whale: the words you'll see on every meme coin page, in one line each.",
    tags: ["beginner", "glossary"],
    takeaways: [
      "A bonding curve sells a new coin directly, raising the price with every buy, until the coin graduates.",
      "Graduation moves a coin from its curve to a regular DEX pool, on sasa with liquidity locked forever.",
      "Market cap is price times circulating supply; liquidity is the money available to trade against.",
      "A rug pull is when the people behind a coin take the money or make it unsellable.",
    ],
    body: [
      { h2: "Launching" },
      { ul: [
        "Launchpad: a site where anyone can create a coin in a few clicks.",
        "Bonding curve: a contract that sells a new coin directly and raises the price with each buy. See [what is a bonding curve](/learn/what-is-a-bonding-curve/).",
        "Graduation: when a coin reaches its target and moves from the curve to a DEX pool. See [graduation explained](/learn/meme-coin-graduation-explained/).",
        "Multi-chain launch: one coin launched on several chains at once. See [multi-chain launch](/learn/multi-chain-token-launch/).",
        "Dev or creator: the wallet that launched the coin.",
        "Dev buy: the creator's own purchase at launch.",
        "Creator lock: the creator's coins can't be sold for a set time.",
        "Ticker: the short symbol of a coin, such as $OTTER.",
        "CA: contract address, the coin's unique address on the chain.",
      ] },
      { h2: "Prices and numbers" },
      { ul: [
        "Market cap (MC): price times circulating supply.",
        "FDV: fully diluted value, price times total supply.",
        "Liquidity: the money in a pool that trades are made against.",
        "Volume: how much was traded in a period, usually 24 hours.",
        "Slippage: the difference between the expected and the actual price of a trade.",
        "Price impact: how much your own trade moves the price.",
        "ATH: all-time high.",
        "Pump: a fast price rise. Dump: a fast fall.",
      ] },
      { h2: "Trading" },
      { ul: [
        "Ape: buy quickly, often without research.",
        "DYOR: do your own research.",
        "Take profit (TP): sell automatically when the value reaches a target.",
        "Stop loss (SL): sell automatically if the value falls to a limit.",
        "Buy the dip: buy automatically after a drop.",
        "Copy trading: following another trader's buys.",
        "Paper hands: sells at the first drop. Diamond hands: holds through drops.",
        "Bag: a position in a coin. Bag holder: someone stuck with a coin that fell.",
        "Exit liquidity: buyers whose money lets earlier holders sell.",
      ] },
      { h2: "Holders and safety" },
      { ul: [
        "Holder map: a picture of who holds a coin and how much.",
        "Top 10 share: how much of the supply the ten biggest wallets hold.",
        "Whale: a wallet holding a large amount.",
        "Sniper: a bot or trader buying in the first seconds of a launch.",
        "Bundle: one person buying through many wallets. See [bundled launches](/learn/bundled-meme-coin-launches/).",
        "Linked wallets: wallets that sent a coin to each other.",
        "Rug pull: the people behind a coin take the money or make it unsellable. See [how to spot a rug pull](/learn/how-to-spot-a-meme-coin-rug-pull/).",
        "Honeypot: a coin you can buy but not sell.",
        "Locked liquidity: pool money that can't be withdrawn.",
        "Mint: creating new coins. A coin with minting turned off has a fixed supply.",
      ] },
      { h2: "Chains" },
      { ul: [
        "Layer 2 (L2): a network built on Ethereum with lower fees, such as Base and Robinhood Chain.",
        "Gas: the network fee for a transaction.",
        "Bridge: moving money between chains.",
        "USDC: a dollar stablecoin, used on sasa for every price, buy and sell.",
        "DEX: a decentralized exchange, such as Uniswap.",
      ] },
    ],
    faq: [
      { q: "What does CA mean in crypto?", a: "Contract address: the unique address of a coin on its chain. Always check it before buying." },
      { q: "What is the difference between market cap and FDV?", a: "Market cap uses the circulating supply; FDV uses the total supply. For most meme coins they are close or equal." },
      { q: "What is a bonding curve?", a: "A contract that sells a new coin directly, raising the price with each buy, until the coin graduates to a DEX pool." },
      { q: "What is a rug pull?", a: "When the people behind a coin take the money or make it impossible to sell." },
    ],
  },
];
