/**
 * More Learn guides (October 2026). Same rules as articles.ts: every claim must
 * be true today (sasa is on testnet; mainnet soon). Links use [words](/path/).
 */
import type { Article } from "./articles";

export const MORE_ARTICLES: Article[] = [
  {
    slug: "bonding-curve-simulator",
    title: "Bonding curve simulator: see what a meme coin buy gets you",
    description:
      "Try a free bonding curve simulator: pick how much a meme coin has raised and how much you buy, and see your coins, price impact and value at graduation.",
    date: "2026-10-01",
    updated: "2026-10-01",
    readMin: 3,
    summary: "Move two sliders and watch the price curve: why early buys get more coins, and what price impact really means.",
    tags: ["bonding-curve", "graduation", "trading"],
    takeaways: [
      "On a bonding curve the price rises with every buy and falls with every sell; nobody sets it by hand.",
      "The same amount of USDC buys more coins early on the curve than late.",
      "Price impact grows with the size of your buy compared with the money already in the curve.",
      "At graduation the coin moves to a locked Uniswap pool at the curve's last price.",
    ],
    body: [
      { p: "A [bonding curve](/learn/what-is-a-bonding-curve/) is the formula that prices a new meme coin before it has a trading pool. The simulator below uses the same formula and the same settings as the sasa contracts, so you can see what a buy does before you make it." },
      { widget: "curve-sim" },
      { h2: "How to read it" },
      { ul: [
        "Already raised: how much money buyers have put into the curve so far. Move it right to see a coin that is further along.",
        "Your buy: the amount you spend, fee included. The quick buttons pick a share of what the coin can still take before it graduates.",
        "You get and share of supply: the coins your buy brings, out of a fixed supply of 1,000,000,000.",
        "Price impact: how much higher your average price is than the price before your buy. Bigger buys move the price more.",
        "Your coins at graduation: what those coins would be worth at the curve's final price, if the coin reaches its target.",
      ] },
      { h2: "Why early buys get more" },
      { p: "The curve works on virtual reserves: an amount of money and an amount of coins whose product never shrinks. Each buy adds money and takes coins out, so the next coin costs a little more. That is why the same buy gets fewer coins the further along a coin is, and why the chart bends upward." },
      { tip: "A coin that is close to its target has less room to rise on the curve. Check the progress bar on the coin page before you buy: [what graduation means](/learn/meme-coin-graduation-explained/)." },
      { h2: "What the simulator can't tell you" },
      { p: "It shows the maths, not the future. Other people's trades change the price before and after yours, a coin may never reach its target, and after graduation the price moves freely in the pool. Treat the numbers as an estimate and only spend what you can afford to lose." },
    ],
    faq: [
      { q: "Is the simulator accurate?", a: "It uses the same formula and the same curve settings as the sasa contracts, read live from the chain. The real result also depends on trades that land before yours." },
      { q: "Does the fee change the result?", a: "Yes. The 1% trading fee is taken on top of the amount that enters the curve, and the simulator includes it." },
      { q: "What happens when a coin graduates?", a: "The money and part of the supply move into a Uniswap pool at the curve's last price, and that liquidity is locked forever. [Graduation explained](/learn/meme-coin-graduation-explained/)." },
      { q: "Why does my buy get fewer coins when the coin has raised more?", a: "Because every buy raises the price for the next one. Later buyers pay more per coin." },
    ],
  },
  {
    slug: "how-to-spot-a-meme-coin-rug-pull",
    title: "How to spot a meme coin rug pull: 9 red flags in 60 seconds",
    description:
      "A 60-second checklist to spot a meme coin rug pull: honeypots, hidden taxes, mint functions, unlocked liquidity, whale wallets and fake volume.",
    date: "2026-10-01",
    updated: "2026-10-01",
    readMin: 8,
    summary: "Nine checks that catch most scams before you buy, and what a safe launch looks like by design.",
    tags: ["safety", "rug-pull", "beginner"],
    takeaways: [
      "Most rug pulls leave visible traces: liquidity that isn't locked, an owner who can mint, taxes that block selling, or a few wallets holding most of the supply.",
      "A honeypot is a coin you can buy but can't sell. Always check that selling is possible before you buy.",
      "Locked or burned liquidity and a fixed supply make the classic rug pull impossible by design.",
      "None of these checks makes a meme coin a good investment; they only remove the most common traps.",
    ],
    body: [
      { p: "A rug pull is when the people behind a coin take the money and leave buyers holding something worthless. It usually happens in one of three ways: they pull the liquidity out of the trading pool, they mint new coins and sell them, or they set up the contract so ordinary buyers can't sell at all. The good news: each of these leaves traces you can check in about a minute, before you spend anything." },
      { h2: "The 60-second checklist" },
      { ol: [
        "Can you sell? A honeypot lets you buy but blocks every sale. Look for a sale simulation in a token checker; on sasa the [Token check](/learn/meme-coin-market-cap-vs-fdv-vs-liquidity/) on each coin page shows whether selling works.",
        "Are there hidden taxes? A 2-5% tax can be normal; a sell tax of 20%, 50% or 99% is a trap. Coins whose sell tax is extreme are never listed on sasa.",
        "Can the owner mint new coins? If the contract has a mint function the owner controls, they can create coins from nothing and sell them into your buy.",
        "Is the liquidity locked or burned? Liquidity is the money in the trading pool. If the creator can withdraw it, the price can go to zero in one transaction.",
        "Who holds the supply? If the top 10 wallets hold most of the coins, a few people can crash the price whenever they want.",
        "Did the creator buy a big share at launch? A large first buy that is not locked is a red flag. On sasa creators can lock their own coins for 1 or 24 hours when they [launch](/create/), and the coin shows a Dev locked badge.",
        "Is the volume real? Compare 24h volume with liquidity and the number of trades. Huge volume with very few traders often means wash trading.",
        "Is the market value plausible? A brand-new meme coin \"worth\" billions with almost no liquidity is broken data or a fake token.",
        "Does the project exist outside the chart? A real X account, an active Telegram and a working website don't guarantee anything, but their absence is telling.",
      ] },
      { tip: "If a coin fails the first four checks, stop there. Those four are how most rug pulls actually happen." },
      { h2: "What a safe launch looks like by design" },
      { p: "The safest launches remove the rug pull options before anyone buys. On sasa every coin has a fixed supply with no owner who can mint, starts on a [bonding curve](/learn/what-is-a-bonding-curve/) you can always sell back to, and [graduates](/learn/meme-coin-graduation-explained/) into a Uniswap pool whose liquidity is locked forever. Nobody, including sasa, can pull that liquidity." },
      { ul: [
        "Fixed supply: no mint function, so no surprise coins.",
        "Sell-back guarantee: before graduation the curve always holds enough to pay every seller.",
        "Locked liquidity: after graduation the pool can't be emptied.",
        "Safety check on every coin page: a plain-language summary of what we checked.",
      ] },
      { h2: "Red flags in how a coin is promoted" },
      { ul: [
        "Promises of guaranteed returns, or of a \"100x\".",
        "Pressure to buy right now, before a supposed listing or announcement.",
        "Anyone asking for your seed phrase or private key, for any reason. No real project ever does.",
        "Copy-cat names of famous coins with a slightly different ticker.",
      ] },
      { h2: "What these checks can't tell you" },
      { p: "A coin that passes every check can still fall 90%. Meme coins are driven by attention, and attention moves on. The checklist protects you from scams, not from the market. Only use money you can afford to lose, and consider [setting a stop loss](/learn/take-profit-stop-loss-meme-coins/) when you buy." },
    ],
    faq: [
      { q: "What is a honeypot token?", a: "A coin whose contract lets you buy but blocks or heavily taxes selling, so your money gets stuck. Token checkers detect it by simulating a sale." },
      { q: "Does locked liquidity mean a coin is safe?", a: "It removes the most common rug pull, pulling the pool's money, but the price can still fall if holders sell. Locked liquidity is necessary, not sufficient." },
      { q: "How can I check who holds a meme coin?", a: "Open the coin's holder list on a block explorer or on the coin page. If a handful of wallets hold most of the supply, be careful." },
      { q: "Can a coin launched on sasa be rugged?", a: "The classic rug pulls are blocked by design: the supply is fixed, the curve always pays sellers, and graduated liquidity is locked forever. Prices can still fall, as with any meme coin." },
    ],
  },
  {
    slug: "meme-coin-graduation-explained",
    title: "Meme coin graduation explained: from bonding curve to Uniswap",
    description:
      "What meme coin graduation means, when it happens, what changes for holders, why liquidity is locked, and how a multi-chain race picks the winner.",
    date: "2026-10-01",
    updated: "2026-10-01",
    readMin: 7,
    summary: "The moment a meme coin leaves its launch curve and becomes a normal, locked trading pool.",
    tags: ["graduation", "bonding-curve", "uniswap"],
    takeaways: [
      "Graduation is when a meme coin reaches its funding target and moves from its launch curve to a regular DEX pool.",
      "On sasa the money and a matching amount of coins become a Uniswap pool at the same price, and that liquidity is locked forever.",
      "Holders keep their coins; nothing needs to be claimed or swapped.",
      "On a multi-chain launch, the chain that raised the most money wins the graduation race.",
    ],
    body: [
      { p: "Most meme coins today start life on a [bonding curve](/learn/what-is-a-bonding-curve/): a contract that sells the coin directly, raising the price with each buy. A curve is a great way to launch with no upfront liquidity, but it isn't meant to last. Graduation is the moment a coin outgrows it." },
      { h2: "When does a meme coin graduate?" },
      { p: "Every coin has a graduation target, a fixed amount of money that buyers must put in. sasa shows it as a progress bar on every coin page and in the [Explore](/explore/) list, with an Almost graduating tab for coins that are nearly there. As soon as the total reaches the target, graduation is triggered automatically." },
      { h2: "What happens at graduation" },
      { ol: [
        "Buying on the curve stops.",
        "The money the curve collected and a matching amount of coins are placed into a new Uniswap pool, at the same price the curve last traded at, so nobody sees a jump.",
        "The pool's liquidity position is locked forever. It can never be withdrawn by the creator, by sasa or by anyone else.",
        "Trading continues in the pool. The coin page and trade box switch over by themselves.",
      ] },
      { tip: "You don't need to do anything at graduation. Your coins stay in your wallet and simply trade in the new pool." },
      { h2: "Why locked liquidity matters" },
      { p: "Liquidity is what lets people sell. If it could be withdrawn, the coin could become unsellable in one transaction, the classic [rug pull](/learn/how-to-spot-a-meme-coin-rug-pull/). Locking it forever turns the pool into permanent infrastructure for the coin. Trading fees in the pool keep flowing as described in the [fees guide](/learn/earn-from-meme-coin-trading-fees/)." },
      { h2: "Graduation on several chains: the race" },
      { p: "A coin launched on [several chains at once](/learn/multi-chain-token-launch/) has one curve per chain but one shared target. Buys on every chain add up, in USDC. When the total reaches the target, the chain holding the most money wins: its curve graduates into a locked pool. Buying stops on the other chains, their money joins the winning pool, and coins held there move automatically to the same address on the winning chain, so nobody has to do anything." },
      { h2: "What to watch after graduation" },
      { ul: [
        "Liquidity: a deeper pool means smaller price moves per trade.",
        "Holders and volume: are new people still arriving? [How to find trending meme coins](/learn/how-to-find-trending-meme-coins-early/) covers the signals.",
        "Price impact on bigger trades: the trade box shows what you'll get before you confirm.",
      ] },
    ],
    faq: [
      { q: "Do I need to claim or swap my coins after graduation?", a: "No. Your coins stay where they are and trade in the new pool automatically." },
      { q: "Does the price drop at graduation?", a: "It shouldn't: the pool is created at the curve's last price. After that, the price moves with supply and demand like any pool." },
      { q: "Can graduated liquidity ever be removed?", a: "Not on sasa. The liquidity position is locked forever by the contract." },
      { q: "What if I hold the coin on the chain that lost the race?", a: "Nothing to do: your coins move automatically to the same address on the winning chain, where they keep trading." },
    ],
  },
  {
    slug: "how-to-buy-meme-coins-with-usdc",
    title: "How to buy meme coins with USDC: no ETH, no bridging, no gas",
    description:
      "Buy meme coins with USDC on Robinhood Chain and Base without ETH, bridging or network fees. Why dollar pricing is simpler, step by step.",
    date: "2026-10-01",
    updated: "2026-10-01",
    readMin: 6,
    summary: "Why pricing everything in dollars makes meme coins simpler, and how to buy your first one.",
    tags: ["usdc", "beginner", "buying"],
    takeaways: [
      "On sasa every meme coin is priced, bought and sold in USDC, a dollar stablecoin.",
      "Signed in with email you don't need ETH for network fees: they're covered for you.",
      "One USDC balance works across chains, and the trade box picks the chain with the best price.",
      "sasa is on testnet today with free test USDC; real USDC comes with mainnet.",
    ],
    body: [
      { p: "Buying a meme coin used to mean three steps before the fun part: buy ETH, bridge it to the right network, keep some back for gas. Each step loses people, and every price is quoted in ETH, which itself moves. Pricing everything in USDC removes most of that friction." },
      { h2: "Why USDC instead of ETH?" },
      { ul: [
        "Prices you understand: a coin's market value, your balance and your profit are all in dollars.",
        "Your cash doesn't move while you wait: holding USDC between trades means no ETH price swings.",
        "One balance for every chain: you don't need separate funds on Robinhood Chain and Base.",
      ] },
      { h2: "How to buy your first meme coin on sasa" },
      { ol: [
        "Sign in with your email. An account is created for you; you don't need a wallet app.",
        "Add USDC with Deposit. On testnet today, Get $100 gives you free test USDC once a day per chain.",
        "Find a coin in [Explore](/explore/) or the [Terminal](/terminal/).",
        "Type an amount in dollars, check what you'll get, and tap Buy. Network fees are covered.",
        "Your balance updates the moment you tap, and the coin appears in your portfolio.",
      ] },
      { tip: "Before you buy, scroll to the coin's safety check. Our [rug pull checklist](/learn/how-to-spot-a-meme-coin-rug-pull/) explains what each line means." },
      { h2: "What about network fees?" },
      { p: "Every transaction on a blockchain pays a network fee. When you sign in with email, sasa covers it, so a $10 buy costs $10 plus the 1% trading fee. If you connect your own wallet instead, you pay network fees yourself, usually cents on Robinhood Chain and Base." },
      { h2: "Selling and taking profit" },
      { p: "Selling works the same way: choose an amount and tap Sell; the proceeds return as USDC. To avoid watching charts all day, set a [take profit or stop loss](/learn/take-profit-stop-loss-meme-coins/) and let it sell for you." },
    ],
    faq: [
      { q: "Do I need ETH to buy meme coins on sasa?", a: "Not when you sign in with email: trades are paid in USDC and network fees are covered. With your own wallet you need a little ETH for fees." },
      { q: "Is the USDC on sasa real?", a: "Not yet. sasa is on testnet and uses free test USDC with no real value. Mainnet will use real USDC." },
      { q: "Which chains can I buy on?", a: "Robinhood Chain and Base today, with more chains planned." },
      { q: "How much does a trade cost?", a: "A 1% trading fee. Network fees are covered for email accounts." },
    ],
  },
  {
    slug: "take-profit-stop-loss-meme-coins",
    title: "Take profit and stop loss for meme coins, explained",
    description:
      "How take profit, stop loss and buy-the-dip orders work for meme coins, how to choose sensible levels, and what auto orders can't promise.",
    date: "2026-10-01",
    updated: "2026-10-01",
    readMin: 7,
    summary: "Automatic orders that sell your gains, cap your losses or buy a dip while you sleep.",
    tags: ["trading", "auto-orders", "risk"],
    takeaways: [
      "A take profit sells automatically when the price rises to your target; a stop loss sells when it falls to your limit.",
      "Buy the dip places a buy that fills only if the price falls to the level you choose.",
      "On sasa sell orders keep your coins in your wallet until they fill; buy-the-dip money is held by the orders contract and can be cancelled.",
      "Meme coins move fast, so an order fills at the next price available, which can differ from your exact level.",
    ],
    body: [
      { p: "Meme coins can double or halve in an hour, often while you're asleep. Auto orders turn a plan into something that runs on its own: sell some when you're up, get out when it turns, or buy when the price comes to you." },
      { h2: "The three order types" },
      { ul: [
        "Take profit: sells when the market value rises to your target, for example +50% or +100%.",
        "Stop loss: sells when it falls to your limit, for example -30%, to cap the damage.",
        "Buy the dip: buys when the price falls to your level. Your USDC waits in the orders contract and comes back if you cancel.",
      ] },
      { h2: "How to set them on sasa" },
      { ol: [
        "Open a coin and choose the Auto tab in the trade box.",
        "Pick the order type and a level. Quick chips like +25%, +50% and +100% fill it in for you.",
        "Choose how much to sell or spend, and confirm.",
        "Your open orders appear on the coin page; cancel or change them any time.",
      ] },
      { tip: "A simple plan many traders use: take back your initial stake at +100%, then let a stop loss protect the rest." },
      { h2: "Choosing sensible levels" },
      { ul: [
        "Leave room for normal swings: a stop at -5% on a meme coin usually triggers on noise.",
        "Split your exits: two take profits at different levels beat one all-or-nothing target.",
        "Mind liquidity: in a thin pool a big sell moves the price. [Market cap vs liquidity](/learn/meme-coin-market-cap-vs-fdv-vs-liquidity/) explains why.",
      ] },
      { h2: "What auto orders can't promise" },
      { p: "Orders are filled by a keeper that watches prices and executes on-chain. If the price gaps past your level in a single trade, your order fills at the next available price, which can be worse than your level. Auto orders reduce how long you need to watch the market; they don't remove risk." },
      { h2: "Combine with the basics" },
      { p: "Auto orders work best on coins that passed the [rug pull checklist](/learn/how-to-spot-a-meme-coin-rug-pull/). A stop loss can't save you from a honeypot that blocks selling." },
    ],
    faq: [
      { q: "Do my coins leave my wallet when I set a take profit?", a: "No. On sasa sell orders use an approval; the coins stay in your wallet until the order fills." },
      { q: "Can I cancel a buy-the-dip order?", a: "Yes, any time before it fills. The USDC held for it returns to you." },
      { q: "Will my stop loss always sell at exactly my price?", a: "Not always. In a fast drop the order fills at the next available price, which can be lower." },
      { q: "Do auto orders cost extra?", a: "No separate fee: the normal 1% trading fee applies when an order fills." },
    ],
  },
  {
    slug: "copy-trading-meme-coins",
    title: "Copy trading meme coins: how to follow top wallets safely",
    description:
      "How meme coin copy trading works, how to pick traders to follow by real results, the risks of copying, and how traders earn from people who copy them.",
    date: "2026-10-01",
    updated: "2026-10-01",
    readMin: 6,
    summary: "Follow traders with a real track record, copy their moves, and avoid the classic mistakes.",
    tags: ["trading", "copy-trading"],
    takeaways: [
      "Copy trading means following a trader's buys and sells with your own money.",
      "Judge traders by realised profit over many trades, not by one lucky win.",
      "Copying adds delay: you buy after them, often at a higher price.",
      "On sasa traders earn a share of sasa's fees from the trades of people who copy them.",
    ],
    body: [
      { p: "Most people who make money on meme coins aren't faster than everyone else; they have a process. Copy trading lets you borrow that process: you follow a trader and their moves become suggestions, or trades, in your own account." },
      { h2: "How to pick a trader to follow" },
      { ul: [
        "Realised profit, not paper gains: what they actually took out.",
        "Many trades over weeks, not one coin that went 50x.",
        "Win rate and size of losses: a good trader cuts losers quickly.",
        "Coins they trade: do they stick to coins that pass basic [safety checks](/learn/how-to-spot-a-meme-coin-rug-pull/)?",
      ] },
      { p: "On sasa the [Top traders](/traders/) leaderboard ranks wallets by results, and each trader's profile shows their history." },
      { h2: "The risks nobody mentions" },
      { ul: [
        "You're always a step behind: when a popular trader buys, followers push the price up before you get in.",
        "Past results don't repeat on command, especially in meme coins.",
        "Position size: a trader risking 1% of a large account and you risking 50% of a small one are not doing the same trade.",
      ] },
      { tip: "Copy with a fixed, small amount per trade and add your own [stop loss](/learn/take-profit-stop-loss-meme-coins/)." },
      { h2: "Getting paid for being copied" },
      { p: "Good traders create value for their followers, so sasa shares fees with them: when someone copies your trade, you earn part of sasa's fee from it. Details are in [how to earn from meme coin trading fees](/learn/earn-from-meme-coin-trading-fees/)." },
    ],
    faq: [
      { q: "Is copy trading profitable?", a: "It can be, but it isn't automatic. You copy someone's decisions, not their results, and you enter after them." },
      { q: "How do I find good traders on sasa?", a: "Use the Top traders leaderboard and open profiles to check realised profit and history over many trades." },
      { q: "Do the traders I copy get anything?", a: "Yes. They earn a share of sasa's fee from the trades their followers copy." },
    ],
  },
  {
    slug: "create-a-meme-coin-with-ai",
    title: "How to create a meme coin with AI in one sentence",
    description:
      "Create a meme coin with AI: one sentence gives you a name, ticker, logo and description in seconds. Good prompts, and what AI can't do.",
    date: "2026-10-01",
    updated: "2026-10-01",
    readMin: 5,
    summary: "From one sentence to a name, ticker, logo and description, then a live coin.",
    tags: ["launch", "ai", "beginner"],
    takeaways: [
      "On sasa you can describe a coin idea in one sentence and AI creates the name, ticker, logo and description.",
      "You can edit anything it suggests before launching.",
      "AI makes the coin look finished; community and timing still decide whether it takes off.",
    ],
    body: [
      { p: "The hardest part of a meme coin launch is usually the blank page: a name that sticks, a ticker that isn't taken, a logo that looks good at 40 pixels. AI handles that part in seconds, so you can spend your energy on the idea and the community." },
      { h2: "Step by step" },
      { ol: [
        "Open [Create a coin](/create/) and choose the AI option.",
        "Describe your idea in one sentence, for example \"a sleepy cat who only wakes up for green candles\".",
        "Review the name, ticker, logo and description it suggests. Edit anything, or generate again.",
        "Add your X, Telegram and website links so buyers can find the community.",
        "Choose your chains and an optional first buy in USDC, and launch.",
      ] },
      { h2: "What makes a good prompt" },
      { ul: [
        "A character or a joke people instantly get.",
        "A mood or style: \"pixel art\", \"80s anime\", \"minimal and bold\".",
        "One clear idea. Prompts that mix five ideas give muddy results.",
      ] },
      { tip: "Say the ticker out loud. If it's hard to say or spell, people won't search for it." },
      { h2: "What AI can't do for you" },
      { p: "AI gives you a finished-looking coin; it can't give you holders. The coins that grow usually have a creator who shows up: posting, answering questions and never promising returns. Read [how to find trending meme coins](/learn/how-to-find-trending-meme-coins-early/) to see what buyers look for, and the [launch guide](/learn/how-to-launch-a-meme-coin-on-robinhood-chain/) for the full process." },
    ],
    faq: [
      { q: "Is creating a meme coin with AI free?", a: "Generating the details is free on sasa, and so is the launch. You only choose how much of your own coin to buy." },
      { q: "Can I change the AI's logo or name?", a: "Yes. Everything is editable before you launch." },
      { q: "Who owns the coin the AI creates?", a: "You do. You launch it from your account and you're its creator, including the creator share of trading fees." },
    ],
  },
  {
    slug: "how-to-find-trending-meme-coins-early",
    title: "How to find trending meme coins early: 7 signals that actually matter",
    description:
      "Find trending meme coins early: read volume, holder growth, buy/sell ratio, liquidity and graduation progress, and spot the fake signals.",
    date: "2026-10-01",
    updated: "2026-10-01",
    readMin: 7,
    summary: "The numbers that show real demand building, and the ones that are easy to fake.",
    tags: ["trading", "discovery", "beginner"],
    takeaways: [
      "Real trends show up as rising volume, a growing number of holders and more buyers than sellers.",
      "Volume without new holders is often a few wallets trading with themselves.",
      "On sasa, Explore and Terminal rank every coin by the same real numbers: volume, 24h change and age.",
      "Early is also riskier: check safety before you chase anything.",
    ],
    body: [
      { p: "Finding a meme coin early isn't about luck; it's about noticing demand while it's still building. A handful of numbers tell you most of the story, and each one is visible on the coin page." },
      { h2: "The 7 signals" },
      { ol: [
        "24h volume rising day over day: people are trading it more, not less.",
        "Holder count growing steadily, not in one jump from a single airdrop.",
        "More buys than sells: the buy/sell bar on each coin page shows it at a glance.",
        "Liquidity that keeps up with market value. A big market value on thin liquidity can collapse fast; see [market cap vs liquidity](/learn/meme-coin-market-cap-vs-fdv-vs-liquidity/).",
        "Graduation progress moving: a coin climbing the Almost graduating tab is attracting real money. [What graduation means](/learn/meme-coin-graduation-explained/).",
        "Wide distribution: no single wallet holding a scary share of the supply.",
        "A community that talks about the coin, not just its price.",
      ] },
      { h2: "Signals that are easy to fake" },
      { ul: [
        "Volume alone: a few wallets can trade back and forth all day.",
        "Huge percentage gains on tiny volume: one small buy can show +300%.",
        "Follower counts and \"partnership\" announcements without links.",
      ] },
      { tip: "On sasa the Top gainers and Top losers tabs only include coins with at least $10K of 24h volume, so one tiny trade can't top the list." },
      { h2: "Where to look on sasa" },
      { ul: [
        "[Explore](/explore/): Trending, New, Almost graduating and Gainers, across every chain.",
        "[Terminal](/terminal/): the top 20 per tab with the chart and trade box on one screen.",
        "Swipe: a fast way to scan coins one by one.",
      ] },
      { p: "Found something? Run the [60-second rug pull check](/learn/how-to-spot-a-meme-coin-rug-pull/), decide your exit before you enter, and set it as an [auto order](/learn/take-profit-stop-loss-meme-coins/)." },
    ],
    faq: [
      { q: "What is the best indicator of a trending meme coin?", a: "No single one. Rising volume together with a growing number of holders and more buys than sells is the strongest combination." },
      { q: "Why do some coins show huge gains but nobody is buying?", a: "Percentage change on very low volume is easy to move. Always look at volume next to the gain." },
      { q: "How does sasa rank coins?", a: "By the same real numbers for every coin, whether it launched on sasa or elsewhere: 24h volume for Trending, 24h change for gainers and losers, and age for Newest." },
    ],
  },
  {
    slug: "meme-coin-market-cap-vs-fdv-vs-liquidity",
    title: "Meme coin market cap vs FDV vs liquidity: what the numbers really mean",
    description:
      "Market cap, FDV, liquidity and volume explained for meme coins: why high market cap on low liquidity is fragile, and how to spot broken numbers.",
    date: "2026-10-01",
    updated: "2026-10-01",
    readMin: 6,
    summary: "Four numbers on every coin page, what each one tells you, and which one matters most when you sell.",
    tags: ["basics", "safety", "trading"],
    takeaways: [
      "Market cap is price times circulating supply; FDV is price times total supply.",
      "Liquidity is the money in the trading pool: it decides how much you can sell without crashing the price.",
      "A big market cap on small liquidity is fragile; a few sells can move it a lot.",
      "Values in the trillions for a new meme coin are broken data or a fake token, not a real valuation.",
    ],
    body: [
      { p: "Every coin page shows a few headline numbers. They look similar but answer different questions, and mixing them up is how people overpay or get stuck." },
      { h2: "Market cap" },
      { p: "Market cap is the current price multiplied by the coins in circulation. It tells you how the market values the coin right now. It's an estimate: if everyone tried to sell at once, nobody would get that price." },
      { h2: "FDV (fully diluted value)" },
      { p: "FDV multiplies the price by the total supply, including coins not in circulation yet. For most meme coins launched on a curve the whole supply exists from day one, so market cap and FDV are close. A big gap means a lot of supply could still enter the market." },
      { h2: "Liquidity" },
      { p: "Liquidity is the money sitting in the trading pool. It's the number that matters when you sell: the deeper the pool, the less each sale moves the price. On graduated sasa coins it's [locked forever](/learn/meme-coin-graduation-explained/)." },
      { h2: "24h volume" },
      { p: "How much was traded in the last day. High volume with growing holders is real interest; high volume with the same few traders can be fake. See [7 signals that actually matter](/learn/how-to-find-trending-meme-coins-early/)." },
      { h2: "Reading them together" },
      { ul: [
        "Market cap far above liquidity (say 50x or more): fragile, expect big price moves.",
        "Volume above liquidity every day: active trading, but also volatile.",
        "Market cap in the trillions on a new meme coin: broken data. sasa hides values like these.",
      ] },
      { tip: "Before a big buy, check what you'd get if you sold the same amount right away. The gap is your real cost of getting in and out." },
    ],
    faq: [
      { q: "Is a low market cap meme coin better?", a: "Not by itself. A low market cap can grow more, but small coins usually have thin liquidity and higher risk." },
      { q: "What is a good liquidity to market cap ratio?", a: "There's no fixed rule, but very low liquidity compared to market cap means prices can move sharply on small trades." },
      { q: "Why does sasa show a dash instead of a market cap?", a: "When the data source reports an impossible value, sasa shows it as unknown instead of a misleading number." },
    ],
  },
  {
    slug: "earn-from-meme-coin-trading-fees",
    title: "How to earn from meme coin trading fees and referrals",
    description:
      "Earn on a meme coin launchpad without trading: creator fee share, 25% referral rewards on friends' trades for a year, and points.",
    date: "2026-10-01",
    updated: "2026-10-01",
    readMin: 6,
    summary: "Where the 1% trading fee goes, and how creators, inviters and copied traders get a share.",
    tags: ["fees", "referral", "earning"],
    takeaways: [
      "Every trade on sasa pays a 1% fee, before and after graduation.",
      "Coin creators earn a share of the fees on their coin.",
      "Inviting friends earns 25% of sasa's fee share on their trades for 12 months.",
      "Traders who get copied earn a share of fees from the trades of people copying them.",
    ],
    body: [
      { p: "Trading isn't the only way to earn on a launchpad. Fees from every trade are shared with the people who bring activity: the creators of coins, the people who invite friends, and the traders others copy." },
      { h2: "Where the 1% fee goes" },
      { p: "Every buy and sell pays 1%. Part goes to the coin's creator, part to sasa. sasa then shares part of its own cut with inviters and copied traders. The same fee continues in the [locked pool after graduation](/learn/meme-coin-graduation-explained/)." },
      { h2: "1. Creator rewards" },
      { p: "Launch a coin and, with the default fee setting, you earn a share of every trade in it for as long as it trades. It's the reason to build a real community instead of a quick flip. Start with [creating a coin with AI](/learn/create-a-meme-coin-with-ai/)." },
      { h2: "2. Referral rewards" },
      { ul: [
        "Share your invite link from the [Points](/points/) page.",
        "Friends who join get a 100-point head start.",
        "You earn 25% of sasa's fee share on their trades for 12 months, plus points.",
        "Rewards are paid out daily in USDC.",
      ] },
      { h2: "3. Getting copied" },
      { p: "If others [copy your trades](/learn/copy-trading-meme-coins/), you earn part of sasa's fee from those copied trades. A good track record becomes an income." },
      { h2: "Points" },
      { p: "Points track activity on sasa: trading, launching, inviting and following us on X. They're a record of early participation." },
      { tip: "sasa is on testnet today, so rewards are paid in free test USDC. The same system runs on mainnet with real USDC." },
    ],
    faq: [
      { q: "How much do I earn from referrals?", a: "25% of sasa's fee share on every trade your invited friends make, for 12 months, paid daily." },
      { q: "Do creators earn after graduation?", a: "Yes. The fee continues in the locked pool, and so does the creator's share." },
      { q: "Are referral rewards paid in USDC?", a: "Yes. On testnet they're paid in test USDC; on mainnet in real USDC." },
    ],
  },
  {
    slug: "robinhood-chain-vs-base-for-meme-coins",
    title: "Robinhood Chain vs Base for meme coins: which should you launch on?",
    description:
      "Robinhood Chain and Base compared for meme coin launches and trading: who uses each, fees, liquidity and launchpads, and why you may not have to choose at all.",
    date: "2026-10-01",
    updated: "2026-10-01",
    readMin: 6,
    summary: "Two low-fee layer 2 networks with different crowds, and how to reach both with one launch.",
    tags: ["robinhood-chain", "base", "multi-chain"],
    takeaways: [
      "Base is Coinbase's layer 2, with a large and established on-chain community.",
      "Robinhood Chain is Robinhood's layer 2, newer, with tokenized stocks and fast-growing meme coin activity.",
      "Both have low fees; the real difference is the audience.",
      "You don't have to choose: a multi-chain launch puts one coin on both.",
    ],
    body: [
      { p: "Both networks are Ethereum layer 2s, so transactions are fast and usually cost cents. For a meme coin, that means the deciding factor isn't the technology; it's who is there to buy." },
      { h2: "Base" },
      { ul: [
        "Built by Coinbase, with a large, active crowd of on-chain users.",
        "A mature meme coin scene with many apps and DEXs.",
        "More competition for attention: a new coin has to stand out among many.",
      ] },
      { h2: "Robinhood Chain" },
      { ul: [
        "Built by Robinhood, newer, home to tokenized stocks alongside meme coins.",
        "A fast-growing meme coin and launchpad scene.",
        "Fewer coins competing for attention than on older chains.",
      ] },
      { h2: "Why choose at all?" },
      { p: "Launching on one chain means only people with funds there can buy. A [multi-chain launch](/learn/multi-chain-token-launch/) puts the same coin on both at once, buys on both count toward one [graduation](/learn/meme-coin-graduation-explained/) target, and the chain that attracts the most money wins." },
      { tip: "On sasa buyers don't need to think about chains: everything is in [USDC](/learn/how-to-buy-meme-coins-with-usdc/) and the trade box picks the best price." },
      { h2: "Quick comparison" },
      { ul: [
        "Fees: low on both.",
        "Audience: Base has a larger established crowd; Robinhood Chain is newer and growing fast.",
        "On sasa: both supported today, with more chains planned.",
      ] },
    ],
    faq: [
      { q: "Is Robinhood Chain or Base cheaper?", a: "Both are layer 2 networks with fees usually measured in cents; the difference rarely matters for a meme coin." },
      { q: "Can one meme coin live on both Robinhood Chain and Base?", a: "Yes. On sasa a multi-chain launch puts it on both, with a shared graduation race that decides where it lives on." },
      { q: "Which chain should I buy on?", a: "On sasa you don't have to decide: the trade box picks the chain with the best price for you." },
    ],
  },
];
